### ISSUE TITLE
想问一个关于微记录的问题，非常抱歉在这里问您

### ISSUE THREAD

**Issue by Nidehuakucha** [xjunz/AutoSkip#22]
我换了两个手机、电脑模拟器都报同一个错误，但其他人都可以正常运行，我太苦恼了。手机是小米8已root安卓10版本，微信8.0.20

f.a.a.i.u$a: cp: bad '/data/user/0/com.tencent.mm/MicroMsg/425d2b2cceb429fa13c014b108485c8c/EnMicroMsg.db': No such file or directory
	at f.a.a.i.u.f(:6)
	at f.a.a.i.u.a(Unknown Source:14)
	at f.a.a.i.u.b(Unknown Source:32)
	at f.a.a.g.a.run(:14)
	at f.a.a.i.c.a(:1)
	at d.a.v.e.a.a.g(Unknown Source:10)
	at d.a.b.a(:2)
	at d.a.v.e.a.e$a.run(Unknown Source:2)
	at d.a.n$a.run(Unknown Source:9)
	at d.a.v.g.l.run(Unknown Source:13)
	at d.a.v.g.l.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Nidehuakucha** [comment]
反馈用的邮箱和qq貌似您都停用了，联系不上您，代码仓库中的问题板块也关闭了，再次非常抱歉在这里问您。
